server:
  port: 8084
  address: 0.0.0.0
  servlet:
    context-path: /mqtt

spring:
  mvc:
    dispatch-options-request: true
  application:
    name: MQTT-SERVICE
  datasource:
    url: ${POSTGRES_URL}
    username: ${POSTGRES_USER}
    password: ${POSTGRES_PASSWORD}
    driver-class-name: org.postgresql.Driver

  jpa:
    show-sql: true
    open-in-view: false
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        enable_lazy_load_no_trans: true
        temp:
          use_jdbc_metadata_defaults: false
        jdbc:
          lob:
            non_contextual_creation: true
        dialect: org.hibernate.dialect.PostgreSQLDialect

mqtt:
  broker:
    url: tcp://14.225.255.177:1883
  client:
    id: mqtt-service
  topic: mqtt/#
  username: admin
  password: admin

management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics
  endpoint:
    health:
      show-details: always
